apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::316554038631:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JTB59U0WV7G0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::316554038631:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-14T19:21:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1639"
  uid: 4f8c3ee3-afeb-40bc-ba43-332438634d9c
